## Vector norm

In [2]:
import numpy as np

In [2]:
v1 = np.array([3,4,5])
v2 = np.array([4,5,6])

In [3]:
v1+v2

array([ 7,  9, 11])

L2 norm

In [4]:
np.linalg.norm(v1)

7.0710678118654755

L1 norm

In [6]:
np.linalg.norm(v2,1)

15.0

Lmax

In [7]:
from math import inf

In [8]:
np.linalg.norm(v2,inf)

6.0

Error Vector

In [9]:
y = np.arange(0,20)
y_hat = np.arange(0,20)*0.5
error_vector = y_hat - y

In [10]:
np.linalg.norm(error_vector)

24.849547279578356

MSE

In [11]:
np.linalg.norm(error_vector)**2/error_vector.shape[0]

30.875000000000007

MAE

In [12]:
np.linalg.norm(error_vector,1)/error_vector.shape[0]

4.75

## Dot product

In [3]:
v1 = np.array([2,3,4])
v2 = np.array([0,9,8])
raw_vec = np.array([[20,30,40]])
col_vec = np.array([[16],
                    [17],
                    [18]])

In [4]:
v1.shape

(3,)

In [5]:
raw_vec.shape

(1, 3)

In [6]:
col_vec.shape

(3, 1)

Dot product

In [7]:
# Both should be in the same size or this form n*k , K*m
v1@v2

59

In [8]:
raw_vec @ col_vec

array([[1550]])

In [9]:
v3 = np.array([[1,2,3]])

In [12]:
v3.T@raw_vec

array([[ 20,  30,  40],
       [ 40,  60,  80],
       [ 60,  90, 120]])

In [21]:
v3.T.shape

(3, 1)

In [23]:
raw_vec.shape

(1, 3)

In [27]:
raw_vec@v3.T

array([[200]])

## System of linear equation

In [28]:
import sympy as sm

In [29]:
# x -2y = 1
# 3x -6y = 11
v = np.array([[1],
              [11]])
A = np.array([[1,-2],
              [3,-6]])


In [30]:
Aug = np.concatenate((A,v),axis=1)

In [31]:
Aug

array([[ 1, -2,  1],
       [ 3, -6, 11]])

In [32]:
M = sm.Matrix(Aug)
M

Matrix([
[1, -2,  1],
[3, -6, 11]])

Reduced Row Echelon Form

In [34]:
M.rref()

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]),
 (0, 2))

- No solution

In [36]:
# x  -2y = 1
# 3x -6y = 3
A = np.array([[1,-2],
              [3,-6]])
v = np.array([[1],
              [3]])
Aug = np.concatenate((A,v),axis=1)

In [37]:
M = sm.Matrix(Aug)
M

Matrix([
[1, -2, 1],
[3, -6, 3]])

In [38]:
M.rref()

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]),
 (0,))

- Has solution

In [39]:
# 4x - 8y = 4
# 3x + 2y = 11
M2 = sm.Matrix([[4,-8,4],
                [3,2,11]])

In [40]:
M2

Matrix([
[4, -8,  4],
[3,  2, 11]])

In [42]:
M2.rref()

(Matrix([
 [1, 0, 3],
 [0, 1, 1]]),
 (0, 1))

x = 3, y=1

In [47]:
v1 = np.array([2,2])
v2 = np.array([-2,2])

In [48]:
v1@v2

0

- Orthogonal vectors : cos 90 = 0