## E matrix using Factorisation

We will try to reflect a vector r in **v** space

In [2]:
import numpy as np

In [9]:
# V space
V = np.array([[1,2,3],
              [1,0,1],
              [1,1,-1]])

In [10]:
Q,R = np.linalg.qr(V) 

In [11]:
Q

array([[-5.77350269e-01,  7.07106781e-01, -4.08248290e-01],
       [-5.77350269e-01, -7.07106781e-01, -4.08248290e-01],
       [-5.77350269e-01, -2.60475187e-17,  8.16496581e-01]])

In [12]:
R

array([[-1.73205081, -1.73205081, -1.73205081],
       [ 0.        ,  1.41421356,  1.41421356],
       [ 0.        ,  0.        , -2.44948974]])

----

## Eignvectors and Eignvalues

In [3]:
# Transformation Matrix
M = np.array([[1,0],
              [1,1]])

In [17]:
eignval,eignvec = np.linalg.eig(M)

In [18]:
eignval

array([1., 1.])

In [19]:
eignvec

array([[ 0.00000000e+00,  2.22044605e-16],
       [ 1.00000000e+00, -1.00000000e+00]])

## Changing to Eign basis "Diagonalization"

$$\mathbf T = CDC^-1$$

If I want to make transformation many times using T matrix, it will be less computationlly expensive to use eign decomposition 

In [38]:
# Transformation Matrix IN orthonormal space
T = np.array([[1,0],
              [1,3]])


In [39]:
eignval,eignvec = np.linalg.eig(T)

In [40]:
C = eignvec

In [41]:
C_inv = np.linalg.inv(C)

In [42]:
D = np.diag(eignval)

In [43]:
D

array([[3., 0.],
       [0., 1.]])

In [52]:
v = np.array([[5],[-1]])

In [61]:
v_new = C@(D**5)@C_inv@v

- Here we multiply T matrix 5 times in eign space then reconvert it to original space

In [62]:
v_new

array([[  5.],
       [362.]])

- This result has less computationally expensive result

In [64]:
np.linalg.matrix_power(T,5)@v

array([[  5],
       [362]])

- This result has high computationally expensive result